// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9v3M3BcK5LLGXZrwWUclkqVOtO6-6K88',
    appId: '1:130614973393:web:4237c61e75ca0fb06b86f0',
    messagingSenderId: '130614973393',
    projectId: 'stuteach-f083d',
    authDomain: 'stuteach-f083d.firebaseapp.com',
    storageBucket: 'stuteach-f083d.appspot.com',
    measurementId: 'G-E80MDMW28N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKbUerYxPYas3C2gD5jrc7IOMPIMGG4SQ',
    appId: '1:130614973393:android:dfe0c9f6ceba5cd86b86f0',
    messagingSenderId: '130614973393',
    projectId: 'stuteach-f083d',
    storageBucket: 'stuteach-f083d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnaRMWJBRdLiXfAbVFjk2JY2xGr5PRKuk',
    appId: '1:130614973393:ios:8e53444d5ae286c56b86f0',
    messagingSenderId: '130614973393',
    projectId: 'stuteach-f083d',
    storageBucket: 'stuteach-f083d.appspot.com',
    iosBundleId: 'com.example.stuTeach',
  );
}
